### ISSUE TITLE
Switch CTS request from javascript to backend call

### ISSUE THREAD

**Issue by annakrohn** [perseids-project/digital_milliet#1]

**Comment by PonteIneptique** [comment]
Documentation has not been updated on [My Capytain Doc](http://mycapytain.readthedocs.org/)
I'll get it done today or tomorrow

**Comment by PonteIneptique** [comment]
[Updated](http://mycapytain.readthedocs.org/en/latest/MyCapytain.resources.texts.html)
Look at api.Passage and api.Text :)
