### ISSUE TITLE
Implement backup for text selections

### ISSUE THREAD

**Issue by annakrohn** [perseids-project/digital_milliet#11]
(Much of this will need to happen on the input side, in perseids_client_apps, https://github.com/annakrohn/perseids-client-apps)

Since there aren't as many TEI texts in the repo that show up in the CTS service, will need to collect and save the text of the passages in the json, so the display is nice and doesn't look like it is completely broken and can't pull texts.

**Comment by balmas** [comment]
Wouldn't it be better to just get those texts converted?

**Comment by balmas** [comment]
this is done.
