### ISSUE TITLE
active language tab should match language displayed

### ISSUE THREAD

**Issue by balmas** [perseids-project/digital_milliet#16]
commit 22d7a4b753bae98ab81cbce40b5b5ff70c66f17d improved language handling but we need to make a tweak to make sure the active tab gets set to the right language

Eg. if an entry has only a french translation and not an english, the english tab is active even though it's the french that is displayed. 

probably a minor javascript fix is all that's required.

**Comment by annakrohn** [comment]
@balmas, if this looks good to you I'll do the pull request and merge.

**Comment by balmas** [comment]
@annakrohn I might be misreading this, but it looks to me like this would set both tabs to active if both translations are present. is this the desired behavior?

**Comment by annakrohn** [comment]
It should break out of the assignment once it hits the first translation that has text, but my js isn't fantastic so I could be wrong.

**Comment by balmas** [comment]
ah, I missed that return statement there. Generally, I think I try to avoid returns out of loop statements. I think I would probably do something like:

```
var available_langs = [];
$('#lang_tabs a').each(function() {
    if ($('#' + this.getAttribute('aria-controls')+ ' p')[0].innerHTML.length > 0) {
        available_langs.push(this);
});
if (available_langs.length > 0) {
    available_langs[0].addClass("active").tab('show');
}
```

It's not as concise, but it makes the intent of the code easier to understand.

**Comment by annakrohn** [comment]
Changed in commit 31a40f51fbf509e4ae307193db2578be76a7cc83.  

The array was being funny though, changes to objects in it didn't seem to effect the DOM, so I instead saved an attribute to use when setting the active tab.

**Comment by balmas** [comment]
ok thanks!  this is fine to merge.
