### ISSUE TITLE
move save_data route from perseids-client-apps into digital_milliet

### ISSUE THREAD

**Issue by balmas** [perseids-project/digital_milliet#18]
the perseids-client-apps should not include mongodb code for committing annotations -- this should be a route in the digital milliet app that the perseids-client-apps does a POST/PUT to

(e.g. this code needs to move 
https://github.com/perseids-project/perseids-client-apps/blob/digmill-deployed/app/views.py#L61-L87)

**Comment by balmas** [comment]
These lines in the perseids-client-apps annotation.py config file would then be changed to point at the urls for save and edit in the digital milliet app:

https://github.com/perseids-project/perseids-client-apps/blob/digmill-deployed/app/configurations/annotation.py#L4-L5

**Comment by annakrohn** [comment]
Work completed in issue18 branch. https://github.com/PerseusDL/digital_milliet/tree/issue18

**Comment by balmas** [comment]
@annakrohn my day got away from me and I didn't have time to do as thorough a review as I want to, but I wanted to give you some quick feedback so that you could move forward. For brevity's sake, I'm putting comments on both the perseids-client-apps and the digital_milliet code here, although it really should be split.  In both cases, I created a codereview branch off of your changes, where I made some very minor changes. 

Digital Milliet Changes
1. Why do you need to create a temp file of the new data? If you do need to do this, at a minimum, the path to where the data is going should be externalized into a config setting, but I'd like to understand more about why it's needed.
2. I think we need a test to make sure the user isn't saving a commentary that already exists. I managed to create 3 versions of the same commentary id in my dev environment.

Perseids Client Apps
1. Rather than displaying the raw json data, why not bring the user directly to the commentary (or edit commentary) view in the Digital Milliet app? This was the purpose of the editorUrl in the other config files (alignment, treebank). After the save data request succeeds in those cases, we just redirect the user to the editing environment for further work.

I unfortunately didn't get a chance to explore the jQuery issue yet, but I will take a look at it next week.

**Comment by annakrohn** [comment]
> I created a codereview branch off of your changes, where I made some very minor changes.

Shall I go ahead and merge?  I'll keep the branch for future changes until I delete these edit branches.

> Why do you need to create a temp file of the new data? If you do need to do this, at a minimum, the path to where the data is going should be externalized into a config setting, but I'd like to understand more about why it's needed.

I had added this as a backup to the mongo db, it probably isn't really necessary.

> I think we need a test to make sure the user isn't saving a commentary that already exists. I managed to create 3 versions of the same commentary id in my dev environment. 

Agreed, I'll add it as an issue.

> Rather than displaying the raw json data, why not bring the user directly to the commentary (or edit commentary) view in the Digital Milliet app? This was the purpose of the editorUrl in the other config files (alignment, treebank). After the save data request succeeds in those cases, we just redirect the user to the editing environment for further work.

That works for me.

**Comment by annakrohn** [comment]
> Rather than displaying the raw json data, why not bring the user directly to the commentary (or edit commentary) view in the Digital Milliet app? This was the purpose of the editorUrl in the other config files (alignment, treebank). After the save data request succeeds in those cases, we just redirect the user to the editing environment for further work.

Thinking more on this, redirecting to the commentary or edit page is going to involve a bit more.  For the sake of workflow it will mean linking back to the initial entry form on perseids-client-apps from the commentary or edit pages, so we are going to need to put in some basic password protection on the entry form, like we do with editing.

**Comment by balmas** [comment]
@annakrohn please do go ahead and merge my changes if you are okay with them.

re the link back to the annotation form, I have already protected that with basic authentication right now (e.g. you should be prompted if you go to http://digmill.perseus.org/annotation)

Eventually both digital milliet edit and the entry form will be able to use perseids user sessions and be protected with oauth.

**Comment by annakrohn** [comment]
@balmas, great.  It seems the only changes from my branches were [updating capitains versions](https://github.com/PerseusDL/digital_milliet/compare/issue18...codereview) and [removing PyMongo](https://github.com/perseids-project/perseids-client-apps/compare/viewsclean...codereview), correct?  

Thank you for confirmation that we've got basic authentication, I'll link everything up!
