### ISSUE TITLE
document the application

### ISSUE THREAD

**Issue by balmas** [perseids-project/digital_milliet#21]
Items to be documented:
- [x] installation
- [x] use cases for the application
- [x] CTS based data entry/edit workflow
- [x] mongodb schema and annotation model
- [x] application/deployment dependencies
- [x] step-by-step guide to using the digital milliet + perseids client apps to create a cts+oa+iiif publication

**Comment by PonteIneptique** [comment]
It would be good to document installation requirements before I take on this task :)

**Comment by balmas** [comment]
Yes I know :-) I'm working on it.
