### ISSUE TITLE
Implement better formatting for text blocks

### ISSUE THREAD

**Issue by annakrohn** [perseids-project/digital_milliet#4]
-bibliography especially, need to add new lines at ; that end a citation, ;\s[A-Z]
-need to handle markdown
-unicode issues?

**Comment by annakrohn** [comment]
Markdown handled in 2b4db078d8d4cb40a78ff5bb458d24721203a01d

**Comment by balmas** [comment]
Related item? https://github.com/perseids-project/perseids-client-apps/issues/20
