### ISSUE TITLE
Security conflicts when logged in if images are served from manifests at http urls not https 

### ISSUE THREAD

**Issue by balmas** [perseids-project/digital_milliet#76]
Logging in to the digital milliet application at https://digmill.perseids.org requires operating under https.  If an entry has been annotated with images served by manifests which are not at https urls, then the images won't load because the browser blocks mixed content. Not sure what the solution is for this but there should be one.

**Comment by PonteIneptique** [comment]
The solution and the only one is to ask provider to go https

**Comment by zfletch** [comment]
The only solution is to use providers that support `http`. Fortunately providers like `https://www.iiifhosting.com/` do support `https`. The user just needs to make sure to enter the URL as `https://free.iiifhosting.com/iiif/:id/info.json` and not `http://`.
